services:
  kindergarten:
    build: .
    depends_on:
      - mysql
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DBNAME: kindergarten
      MYSQL_USER: root
      MYSQL_PASSWORD: 28122003
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 28122003
      MYSQL_DATABASE: kindergarten
    ports:
      - 3307:3306